# Generated by Django 5.2.6 on 2025-10-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_intentologin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
