# Generated by Django 5.2.6 on 2025-11-04 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_email_alter_empresa_telefono'),
        ('login', '0005_alter_perfil_bio_alter_perfil_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='empresa.empresa', verbose_name='Empresa'),
        ),
    ]
