# Generated by Django 5.2.6 on 2025-10-12 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código de Cuenta')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Cuenta')),
                ('tipo', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('PT', 'Patrimonio'), ('I', 'Ingreso'), ('G', 'Gasto'), ('C', 'Costo')], max_length=2, verbose_name='Tipo de Cuenta')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nivel')),
                ('naturaleza', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10, verbose_name='Naturaleza')),
                ('acepta_movimiento', models.BooleanField(default=True, verbose_name='Acepta Movimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='cuentas.cuenta', verbose_name='Cuenta Padre')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='empresa.empresa')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
