# Generated by Django 5.2.6 on 2025-10-24 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cuentas.cuenta')),
                ('es_corriente', models.BooleanField(default=True, verbose_name='Es Corriente')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
            bases=('cuentas.cuenta',),
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cuentas.cuenta')),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costos',
            },
            bases=('cuentas.cuenta',),
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cuentas.cuenta')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
            bases=('cuentas.cuenta',),
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cuentas.cuenta')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
            },
            bases=('cuentas.cuenta',),
        ),
        migrations.CreateModel(
            name='Pasivo',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cuentas.cuenta')),
                ('es_corriente', models.BooleanField(default=True, verbose_name='Es Corriente')),
            ],
            options={
                'verbose_name': 'Pasivo',
                'verbose_name_plural': 'Pasivos',
            },
            bases=('cuentas.cuenta',),
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('cuenta_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cuentas.cuenta')),
            ],
            options={
                'verbose_name': 'Patrimonio',
                'verbose_name_plural': 'Patrimonios',
            },
            bases=('cuentas.cuenta',),
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='activo',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='esta_activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
