# Generated by Django 5.2.6 on 2025-10-12 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0001_initial'),
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número de Comprobante')),
                ('tipo', models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('NC', 'Nota Contable'), ('A', 'Apertura'), ('C', 'Cierre')], max_length=2, verbose_name='Tipo de Comprobante')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('total_debito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Débito')),
                ('total_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Crédito')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADO', 'Aprobado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='empresa.empresa')),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('empresa', 'tipo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='DetalleComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Débito')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédito')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='transacciones.comprobante')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='cuentas.cuenta')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante',
                'verbose_name_plural': 'Detalles de Comprobantes',
                'ordering': ['orden'],
            },
        ),
    ]
